/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alanjet_videorecordertest_OpenCVHelper */

#ifndef _Included_com_alanjet_videorecordertest_OpenCVHelper
#define _Included_com_alanjet_videorecordertest_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alanjet_videorecordertest_OpenCVHelper
 * Method:    computeXYZ
 * Signature: ([II)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_alanjet_videorecordertest_OpenCVHelper_computeXYZ
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_alanjet_videorecordertest_OpenCVHelper
 * Method:    computeXYZtest
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_alanjet_videorecordertest_OpenCVHelper_computeXYZtest
  (JNIEnv *, jclass);

/*
 * Class:     com_alanjet_videorecordertest_OpenCVHelper
 * Method:    toAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alanjet_videorecordertest_OpenCVHelper_toAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
